### ISSUE TITLE
Fix route in deploy.sh

### ISSUE THREAD

**Issue by trozet** [trozet/bgs_vagrant#12]
https://github.com/trozet/bgs_vagrant/blob/master/deploy.sh#L323
We currently use "route" to get the default gateway.  It turns out this sometimes will return a hostname for a default gateway and not an ip address.  It looks like using "ip route" gets around this problem:

host_default_gw=$(ip route | grep default | awk '{print $3}')

**Comment by pbandzi** [comment]
or 
'route -n'
 -n     show numerical addresses instead of trying to determine symbolic host names.

host_default_gw=$(route -n | grep default | awk '{print $2}')

**Comment by trozet** [comment]
@pbandzi mentioned we can do this:
'route -n'
-n show numerical addresses instead of trying to determine symbolic host names.

host_default_gw=$(route -n | grep default | awk '{print $2}')

Will patch it to use this.

**Comment by trozet** [comment]
Actually used "ip route" listed in the original comment as the fix.  "route -n" removes the default keyword and lists 0.0.0.0 which makes things harder to parse.  Fixed and closing.
