### ISSUE TITLE
deployment doesn't stop

### ISSUE THREAD

**Issue by pbandzi** [trozet/bgs_vagrant#17]
When installation of node is done it should inform Foreman. There is a wget command in kickstart file which should do this.

this is how it looks in my env:

```
echo "Informing Foreman that we are built"
wget -q -O /dev/null --no-check-certificate http://foreman-server.opnfv.com:80/unattended/built?token=45da12c4-e91a-4315-b77c-e3d0170b5e4f
```

I put 'sleep 3h' into kickstart 
then i observed following message occurs right before 'Informing foreman that we are built'

```
Exiting; failed to retrieve certificate and waitforcert is disabled
```

Seems like certificate issue between puppet master and agent

after that I can do manualy:

```
wget --no-check-certificate http://foreman-server.opnfv.com:80/unattended/built
```

and then when reboot, it will boot from disk. (then i see puppet errors but that's another issue :smile: )

**Comment by pbandzi** [comment]
certificate issue is not relevant it was caused by previous installation. There was need to clean it on foreman node before build start again:

```
puppet cert clean oscontroller1.opnfv.com
```

**Comment by pbandzi** [comment]
Thanks to Tim advice to use wget with --no-proxy option in kicstart file
Now the issue is solved.

**Comment by trozet** [comment]
Closing this issue and will add the wget with --no-proxy option to the proxy issue fix.
