### ISSUE TITLE
Issue with HA and rabbit

### ISSUE THREAD

**Issue by ibravo** [trozet/bgs_vagrant#21]
Having an issue with HA, I believe.

I am getting the following error in foreman server:

Failed to parse inline template: no implicit conversion from nil to integer at /usr/share/openstack-foreman-installer/puppet/modules/quickstack/manifests/pacemaker/rabbitmq.pp:17 on node oscontroller3.opnfv.com

I'm getting the same error on my three nodes. (oscontroller 1, 2 & 3)

**Comment by trozet** [comment]
Hi @ibravo,
This normally means there is a conflict between the private IP being handed to the controllers vs. the IPs the controllers should have had.  If you check Foreman global paramter controllers_ip_array you will see the IPs the controllers should have.  If the IP of your controller is not in that array then that is why you are getting that error.  To double check what deploy setup for dhcp: on your Foreman VM cat /etc/dhcpd/dhcp.hosts

This will show you the static private ip addresses and MACs.  I'm guessing the mac you provided is incorrect or the port that is connected is the wrong port/VLAN.

**Comment by ibravo** [comment]
Tim,

Thanks for your response. The problem was that I was not correctly segregating the NICs in different VLANs.
Once I assigned them to the correspondent VLAN, it was all good.

Thanks,
IB
